# Список наших сервисов (контейнеров)
version: "3.5"

services:
    # Apache + PHP
    www:
        build:
            context: .docker/images/php
        restart: unless-stopped
        ports:
            - 80:80
        networks:
            - dockernet
        volumes:
            # Рабочая директория
            - ./:/var/www/html
            # Конфиги
            - .docker/conf/apache2.conf:/etc/apache2/apache2.conf
            - .docker/conf/php.ini:/usr/local/etc/php/php.ini
            - ./.docker/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            # Логи
            - .docker/logs:/var/log/apache2

# Сеть между контейнерами
networks:
    dockernet:
        driver: bridge
