index:
    path: /
    controller: App\Controller\AppController::index
edit:
    path: /edit/{id}
    controller: App\Controller\AppController::edit

save:
    path: /save
    controller: App\Controller\AppController::save
